version: "3.8"

services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        restart: always
        environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=ithingv@admin.com
            - PGADMIN_DEFAULT_PASSWORD=password
        ports:
            - 5050:80
        depends_on:
            - pgdb